development:
  facebook:
    app_id: "144574445744603"
    app_secret: "501bf4e3202cd8578e32232a4a3c2d59"
    options:
      scope: "email"
      display: "page"

staging: &staging
  facebook:
    app_id: "144574445744603"
    app_secret: "501bf4e3202cd8578e32232a4a3c2d59"
    options:
      scope: "email"
      display: "page"

test:
  <<: *staging

production:
  facebook:
    app_id: "144574445744603"
    app_secret: "501bf4e3202cd8578e32232a4a3c2d59"



